../bin/airgabe BOOK A0 1
../bin/airgabe CANCEL A0 1
../bin/airgabe BOOK A0 1
../bin/airgabe BOOK A0 1
../bin/airgabe BOOK A1 1
../bin/airgabe BOOK A2 4
../bin/airgabe BOOK A5 1
../bin/airgabe BOOK A6 3
../bin/airgabe BOOK A8 1
../bin/airgabe BOOK U1 1